// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8_J3BCRWQelRn4acAGdJ0Xlp7jnHGuHQ',
    appId: '1:253739597243:android:95252cafa23c05bdf1189e',
    messagingSenderId: '253739597243',
    projectId: 'pawpocket-34267',
    storageBucket: 'pawpocket-34267.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbacNuXbwTjuBoxTjdpXIq3tVyvcUGFQo',
    appId: '1:253739597243:ios:0c18b8171d3cf555f1189e',
    messagingSenderId: '253739597243',
    projectId: 'pawpocket-34267',
    storageBucket: 'pawpocket-34267.firebasestorage.app',
    iosBundleId: 'com.example.pawpocket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh1PajZu82df2tX27YXZyw8YU6CiEDowc',
    appId: '1:253739597243:web:bb409ee74787ed1ef1189e',
    messagingSenderId: '253739597243',
    projectId: 'pawpocket-34267',
    authDomain: 'pawpocket-34267.firebaseapp.com',
    storageBucket: 'pawpocket-34267.firebasestorage.app',
    measurementId: 'G-9RGH23PCRY',
  );
}
